name: ci 
on:
  push:
    branches:
      - master 
  workflow_dispatch:  
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la  

      - name: Generate package.json
        run: |
          echo '{
            "name": "your-project-name",
            "version": "1.0.0",
            "description": "Your project description",
            "main": "index.js",
            "scripts": {
              "build": "pageforge build",
              "start": "node index.js"
            },
            "dependencies": {},
            "devDependencies": {}
          }' > package.json

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
        
      - name: Install dependencies
        run: pnpm install  

      - name: Build site
        run: |
          pnpm run build  # 使用 pnpm 运行构建命令

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  
